### ISSUE TITLE
Adjust 1D-2C

### ISSUE THREAD

**Issue by bhamrick** [bhamrick/precision_system#39]
Our current 1D-2C bid feels not very useful (we have better ways to find 4-4 major fits while still game forcing now by starting with 1H). My suggestion is inv+ 5+ clubs and one round forcing, similar to an inverted minor raise of a short club. It may be useful to have some artificiality in the rebids to get more information before ending in 2NT (We won't worry about stopping in 2D, so 2D can be artificial).

Some discussion in a standard context: https://bridgewinners.com/article/view/the-1d-2c-problem/

**Comment by shewu** [comment]
> we have better ways to find 4-4 major fits while still game forcing now by starting with 1H

I do agree that we have better ways to find 4-4 major fits. Regarding game forcing once a 4-4 major fit is found, what is opener bidding after the 1H response to game force?

> My suggestion is inv+ 5+ clubs and one round forcing

I do like 5+ clubs. Not sure about the one-round forcing; is the cost of playing in 3C vs 2C overshadowed by the benefits of a response? The only other strain which we can go is NT (since the 4-4 major fit is found with 1H/1S), unless we are considering a 4-3 fit in the majors at the 2 level?

**Comment by bhamrick** [comment]
> > we have better ways to find 4-4 major fits while still game forcing now by starting with 1H
> 
> I do agree that we have better ways to find 4-4 major fits. Regarding game forcing once a 4-4 major fit is found, what is opener bidding after the 1H response to game force?

Opener doesn't do a game force. Opener is limited by the opening bid.
Responder bids 4H usually, but all the game try systems work for slam trying as well, and then responder can bid keycard etc.
> 
> > My suggestion is inv+ 5+ clubs and one round forcing
> 
> I do like 5+ clubs. Not sure about the one-round forcing; is the cost of playing in 3C vs 2C overshadowed by the benefits of a response? The only other strain which we can go is NT (since the 4-4 major fit is found with 1H/1S), unless we are considering a 4-3 fit in the majors at the 2 level?

The alternative to one round forcing would be game forcing, not nonforcing. Otherwise what would a hand with clubs and 15+ points do?

But yes, I think 2H and 2S rebids can be artificial.

**Comment by bhamrick** [comment]
Here's a sketch of a possibility (and possibly we should do something similar for 1D-2D which is also 5+ card forcing 1 round):

1D-2C-?
* 2D = any minimum
* 2H = max with 4 hearts
* 2S = max with 4 spades
* 2NT = max with 4/4 majors (implies 2/3 in minors either way)
* 3C = max with 4+ clubs
* 3D = max with diamond primary hand (5+, often 6), denies 4+ club support

Rather than showing 4 card majors, may be worth showing stoppers or something else.

1D-2C-2D-?
* 2H Asks, still not GF
* 2S GF, maybe a puppet to 2NT?
* 2NT alternate GF?

The 2S and 2NT sequences here could be useful in getting the inevitable 3NT contract declared from the correct side.

1D-2C-2D-2H-?
* 2S = Balanced, no reason to declare in NT
* 2NT = Balanced, prefer to be declarer in NT (e.g. have an unguarded king in the short major)
* 3C = Club support
* 3D = 6+ Diamonds

One thing to aim for when designing the system here is that if we end up in game it will usually be 3nt, so it's useful to try to get the 3nt contract played from the correct side. We want to be able to find minor fits so that later we can add something like kickback for finding minor slams.

Thoughts?

**Comment by shewu** [comment]
> 2NT = max with 4/4 majors (implies 2/3 in minors either way)
> 3D = max with diamond primary hand (5+, often 6), denies 4+ club support

4450 should go through 2NT instead of 3D. 4441 is also possible for 2NT. 44(23) max should go through 1NT opener.

Overall, worth trying as our current 2C is used rarely.

**Comment by shewu** [comment]
Same for 1D-2D response, which is also used rarely.
