### ISSUE TITLE
Consider mini notrump openings

### ISSUE THREAD

**Issue by bhamrick** [bhamrick/precision_system#42]
A 10-12 notrump opening in 1st/2nd seat nonvul seems appealing as an aggressive preemptive bid, and it makes the other openings a more uniform in strength because an unbalanced hand is generally stronger than a balanced hand, so 11-15 unbalanced or 13-15 balanced is more tightly packed.

Example system (responder is often stronger, so no transfers):
* 2C = stayman, possibly garbage
* 2D = some sort of game forcing ask
* 2H = to play
* 2S = to play

We would need to decide on a runout system (what to do when opponents make a penalty double).

**Comment by shewu** [comment]
Let's try it. Runout can reuse our defense against strong NT.
