### ISSUE TITLE
Consider replacing gerber with south african texas

### ISSUE THREAD

**Issue by bhamrick** [bhamrick/precision_system#43]
South African Texas transfers is:
* 4C transfers to 4H
* 4D transfers to 4S
* 4H is to play
* 4S is to play

The advantage is that you can transfer or not depending on whether you need to protect a stopper. It also would mean that the system translates better to a weak notrump if we adopt that, which eases memory concerns (since you will generally prefer to not transfer as responder is stronger than opener in that case).

**Comment by shewu** [comment]
Sounds good. Gerber hasn't been very useful so far.
